apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: learn-operator
  template:
    metadata:
      labels:
        name: learn-operator
    spec:
      serviceAccountName: learn-operator
      containers:
        - name: learn-operator
          # Replace this with the built image name
          image: quay.io/jiazha/learn-operator
          command:
          - learn-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "learn-operator"
